### ISSUE TITLE
Improve generated generatedAtTime property

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESWorkbench-NiFi#26]
Change property `Add top-level 'generatedAt' property`
- rename to `GeneratedAtTime property`
- possible values are URIs
- use the entered value as the property name
- default value: `http://www.w3.org/ns/prov#generatedAtTime`
- can be left empty
- use the entered value as the property name
- do not add this property if empty value is set
- ensure the property value is a `xsd:dateTime`, e.g. `"2022-10-03T13:35:23Z"^^xsd:dateTime` (currently missing)

**Comment by Yalz** [comment]
To put this in a more logical perspective, what I read here:

if the value is filled in (then it must be a valid URI):
   use the value to add the generatedAtTime property.
If the value is not filled in:
   use the default value "http://www.w3.org/ns/prov#generatedAtTime"
If the value is put to empty
   do not add the property

Unfortunately, since it can be both empty and a URI, a validation on URI can not be added
